### ISSUE TITLE
Disable the hideMonthView

### ISSUE THREAD

**Issue by mc6ril** [noona-hq/react-native-week-month-date-picker#10]
Hi ! 

Is there a way to add the possibility to disable the hideMonthView function when we are into the month View ? 
When I click on a date, i don't want to reopen the month view.

Thanks for your time !

**Comment by gunnartorfis** [comment]
Hi! Sorry for the late response. I have to configure my notifications better. 

That sounds like a sensible configuration. Do you mind open up a PR for it?
