### ISSUE TITLE
Change Selected Day Color

### ISSUE THREAD

**Issue by cbaser** [noona-hq/react-native-week-month-date-picker#11]
Hi,
How can change the selected day color?
Currently I can change only the primaryColor in theme. 
Can you also update this as well?
Thank you for your work and effort!
Cheers!

**Comment by gunnartorfis** [comment]
Hey there. It's not possible at the moment. 

Feel free to make a PR, I'll review it and merge it right away. 
https://github.com/noona-hq/react-native-week-month-date-picker/blob/main/src/components/DatePickerItem/index.tsx
