### ISSUE TITLE
Crash when opening the calendar

### ISSUE THREAD

**Issue by OstinPower41016** [noona-hq/react-native-week-month-date-picker#14]
![image](https://github.com/gunnartorfis/react-native-week-month-date-picker/assets/63050019/658ac38d-e37d-4f53-842a-ed1ee854d023)

Exception	NSException *	"Mouting block is expected to not be set"	0x0000600003650c00

![image](https://github.com/gunnartorfis/react-native-week-month-date-picker/assets/63050019/c6d8551f-76c0-4731-8dad-6861f386ca33)

**Comment by gunnartorfis** [comment]
This is a native crash report. This library doesn't have any native dependencies, so the issue lies with some other library or your code.
