### ISSUE TITLE
Question, where would a "done" button go?

### ISSUE THREAD

**Issue by Seanmclem** [noona-hq/react-native-week-month-date-picker#8]
where would a "done" button go? Like, after I’m done selecting my date, I’m sure there’s a way to dismiss the Picker. Where would the button to do that, go? Is there a way to show or position such a button?

Thanks!

**Comment by gunnartorfis** [comment]
Hi!
If you're talking about the "Month view", it should dismiss when you select a date. Is that not the experience you're seeing?

Please send me the code snippet you're using 😀

**Comment by Seanmclem** [comment]
> Hi!
> If you're talking about the "Month view", it should dismiss when you select a date. Is that not the experience you're seeing?
> 
> Please send me the code snippet you're using 😀 

No I'm talking about the picker in general. It can't be visible 100% of the time. How would you sjoe and hide it

**Comment by gunnartorfis** [comment]
You could have a `React.useState` hook that controls the visibility:

```ts
const [datePickerVisible, setDatePickerVisible] = React.useState(false);

return (
  <SafeAreaView style={{ flex: 1}}>
    <Button title="Toggle Date Picker" onPress={() => setDatePickerVisible(!datePickerVisible)} />
    {datePickerVisible ? <DatePicker {...} /> : null}
  </SafeAreaView>
)

```
